# Generated by Django 2.1.15 on 2020-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0005_auto_20200830_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
