# Generated by Django 2.1.15 on 2020-09-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
