# Generated by Django 2.1.15 on 2020-09-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0007_auto_20200905_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
