# Generated by Django 2.1.15 on 2020-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0014_auto_20200906_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
