# Generated by Django 2.1.15 on 2020-09-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0015_auto_20200906_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
