# Generated by Django 2.1.15 on 2020-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0017_auto_20200906_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbBroj',
            field=models.IntegerField(default=0),
        ),
    ]
