# Generated by Django 2.1.15 on 2020-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0018_post_thumbbroj'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='redni',
            field=models.IntegerField(default=0),
        ),
    ]
