# Generated by Django 2.1.15 on 2020-09-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0019_postimage_redni'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/')),
                ('redni', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='novosti.Post')),
            ],
        ),
    ]
